services:
  event-svc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event_svc_app
    ports:
      - "3002:3002"
    environment:
      MONGO_URL: mongodb://host.docker.internal:27017
      DB_NAME: event_svc
      EVENTS_COLLECTION: events
      AUTH_SERVICE_URL: http://host.docker.internal:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"
